---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
- name: Message check rtpengine package
  debug:
    msg:
      - "ngcp-rtpengine package exist"
  when: ( hostvars['{{ ip_server }}']['ansible_facts']['packages'].keys() | select('search', '^ngcp-rtpengine$') | list ) != ""
- name: Check if {{ rtpengine_path }} exist
  stat:
    path: "{{ rtpengine_path }}"
  register: rtpengine_path_check
- name: Message check {{ rtpengine_path }}
  debug:
    msg:
      - "{{ rtpengine_path }} exist"
  when: 
    - rtpengine_path_check.stat.exists
    - rtpengine_path_check.stat.isdir
- name: Add line restore directory $BACKUP_RESTORE_PATH/rtpengine/
  blockinfile:
    path: /opt/restore-system.sh
    marker: "# Tuan restore rtpengine config"
    insertafter: EOF
    block: |
      tar -xzvf $BACKUP_RESTORE_PATH/*-rtpengine-$NOW.tar.gz -C $BACKUP_RESTORE_PATH/rtpengine
      mv {{ rtpengine_path }} {{ rtpengine_path }}.$TIME.bak
      mv $BACKUP_RESTORE_PATH/rtpengine {{ rtpengine_path }}
      systemctl restart ngcp-rtpengine-daemon
    state: present
  when:
    - ( hostvars['{{ ip_server }}']['ansible_facts']['packages'].keys() | select('search', '^ngcp-rtpengine$') | list ) != ""
    - rtpengine_path_check.stat.exists
    - rtpengine_path_check.stat.isdir
...